# Generated by Django 5.1.15 on 2026-09-08 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_guardpair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('qr_code', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='stations.station')),
            ],
            options={
                'ordering': ['station', 'order'],
                'unique_together': {('station', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PatrolLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_logs', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_logs', to='stations.station')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('gps_coords', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.CharField(blank=True, default='Checkpoint secure.', max_length=255)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='patrols.checkpoint')),
                ('patrol_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='patrols.patrollog')),
            ],
            options={
                'ordering': ['scanned_at'],
            },
        ),
    ]
