# Generated by Django 5.1.15 on 2026-10-05 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='min_interval_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Minimum transit/travel time in seconds required from previous checkpoint.'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='nfc_uid',
            field=models.CharField(blank=True, default='', help_text='Registered hardware NFC UID for physical checkpoint verification.', max_length=64),
        ),
        migrations.AddField(
            model_name='patrollog',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrollog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_patrols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patrollog',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
