# Generated by Django 5.1.15 on 2026-10-05 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0002_checkpoint_min_interval_seconds_checkpoint_nfc_uid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointscan',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkpointscan',
            name='client_event_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='checkpointscan',
            name='client_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkpointscan',
            name='verification_method',
            field=models.CharField(default='UNVERIFIED', max_length=30),
        ),
        migrations.AddField(
            model_name='patrollog',
            name='anomalies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patrollog',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patrols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patrollog',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrollog',
            name='name',
            field=models.CharField(default='Routine Station Patrol', max_length=150),
        ),
        migrations.AddField(
            model_name='patrollog',
            name='start_window',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrollog',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved')], default='ASSIGNED', max_length=20),
        ),
    ]
