# Generated by Django 5.1.15 on 2026-09-08 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='casual_accrual_rate',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='casual_cycle_start',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='casual_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='last_accrual_date',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='used_casual',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='used_vacation',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='vacation_accrual_rate',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='vacation_cap',
            field=models.DecimalField(decimal_places=1, default=90.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='vacation_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('VACATION', 'Vacation Leave'), ('ANNUAL', 'Vacation Leave (Legacy Annual)'), ('SICK', 'Sick Leave'), ('EMERGENCY', 'Emergency Leave'), ('COMPASSIONATE', 'Compassionate Leave')], default='VACATION', max_length=20),
        ),
    ]
