# Generated by Django 5.1.15 on 2026-09-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavebalance_casual_accrual_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='emergency_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
