# Generated by Django 5.1.15 on 2026-09-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaveapplication_emergency_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('MANPOWER_SHORTAGE', 'Manpower shortage'), ('CRITICAL_SCHEDULE', 'Critical Schedule'), ('INSUFFICIENT_DAYS', 'Insufficient days'), ('SPECIAL_FUNCTIONS', 'Special Upcoming functions'), ('OTHER', 'Other operational grounds')], default='', max_length=50),
        ),
    ]
