# Generated by Django 5.1.15 on 2026-09-18 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaveapplication_rejection_reason'),
        ('shifts', '0004_publicholiday_publicholidaydutyrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('VACATION', 'Vacation Leave'), ('COMPENSATION', 'Public Holiday Compensation'), ('ANNUAL', 'Vacation Leave (Legacy Annual)'), ('SICK', 'Sick Leave'), ('EMERGENCY', 'Emergency Leave'), ('COMPASSIONATE', 'Compassionate Leave')], default='VACATION', max_length=20),
        ),
        migrations.CreateModel(
            name='PublicHolidayCompensationLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('EARNED', 'Earned (Public Holiday Duty)'), ('USED', 'Used (Compensatory Leave Taken)')], db_index=True, max_length=20)),
                ('days', models.DecimalField(decimal_places=1, max_digits=6)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compensation_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('duty_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensation_ledger_entries', to='shifts.publicholidaydutyrecord')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('leave_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensation_ledger_entries', to='leave.leaveapplication')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('entry_type', 'EARNED')), fields=('duty_record', 'entry_type'), name='unique_earned_entry_per_duty_record'), models.UniqueConstraint(condition=models.Q(('entry_type', 'USED')), fields=('leave_application', 'entry_type'), name='unique_used_entry_per_leave_application')],
            },
        ),
    ]
