# Generated by Django 5.1.15 on 2026-09-27 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leaveapplication_leave_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='doctor_report',
            field=models.TextField(blank=True, default='', help_text='Medical certificate or doctor report details for Sick Leave'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='doctor_report_verified',
            field=models.BooleanField(default=False, help_text='Verified by reviewing supervisor'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='event_details',
            field=models.TextField(blank=True, default='', help_text='Event justification for Special Leave'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('VACATION', 'Vacation Leave'), ('COMPENSATION', 'Public Holiday Compensation'), ('SPECIAL', 'Special Leave'), ('SICK', 'Sick Leave'), ('ANNUAL', 'Vacation Leave (Legacy Annual)'), ('EMERGENCY', 'Emergency Leave'), ('COMPASSIONATE', 'Compassionate Leave')], default='VACATION', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveAccrualRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('month', models.PositiveIntegerField(db_index=True)),
                ('casual_credited', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('vacation_credited', models.DecimalField(decimal_places=1, default=2.5, max_digits=4)),
                ('casual_balance_after', models.DecimalField(decimal_places=1, max_digits=6)),
                ('vacation_balance_after', models.DecimalField(decimal_places=1, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_accruals', to=settings.AUTH_USER_MODEL)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('guard', 'year', 'month'), name='unique_accrual_record_per_guard_month')],
            },
        ),
    ]
