# Generated by Django 5.1.15 on 2026-09-28 14:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leaveapplication_doctor_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='opening_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='opening_balance_source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='opening_balance_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_leave_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='opening_casual_balance',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='opening_vacation_balance',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6),
        ),
        migrations.CreateModel(
            name='LeaveAdjustmentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance Reconciliation'), ('ADMINISTRATIVE_ADJUSTMENT', 'Administrative Adjustment')], default='OPENING_BALANCE', max_length=30)),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('VACATION', 'Vacation Leave'), ('COMPENSATION', 'Public Holiday Compensation'), ('SPECIAL', 'Special Leave'), ('SICK', 'Sick Leave'), ('ANNUAL', 'Vacation Leave (Legacy Annual)'), ('EMERGENCY', 'Emergency Leave'), ('COMPASSIONATE', 'Compassionate Leave')], max_length=20)),
                ('previous_balance', models.DecimalField(decimal_places=1, max_digits=6)),
                ('new_balance', models.DecimalField(decimal_places=1, max_digits=6)),
                ('effective_date', models.DateField(db_index=True)),
                ('source', models.CharField(default='Existing organisational record', max_length=200)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_leave_adjustments', to=settings.AUTH_USER_MODEL)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
