# Generated by Django 5.1.15 on 2026-10-06 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_leavebalance_opening_balance_date_and_more'),
        ('shifts', '0006_dutyoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholidaycompensationledger',
            name='duty_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_ledger_entries', to='shifts.dutyoverride'),
        ),
    ]
