services:
  - type: web
    name: sgmis-api
    runtime: python
    rootDir: backend
    plan: free
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    healthCheckPath: /health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: SGMIS_INITIAL_ADMIN_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
