# Generated by Django 5.1.15 on 2026-09-08 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rotation_order', models.PositiveIntegerField(db_index=True, default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guard_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_guard_a', to=settings.AUTH_USER_MODEL)),
                ('guard_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_guard_b', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='stations.station')),
            ],
            options={
                'ordering': ['station', 'rotation_order'],
                'unique_together': {('station', 'rotation_order')},
            },
        ),
    ]
