# Generated by Django 5.1.15 on 2026-10-06 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_guardpair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardPairReassignmentAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_date', models.DateField(db_index=True)),
                ('reason', models.TextField(help_text='Mandatory operational justification for pair reassignment')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_pair_reassignments', to=settings.AUTH_USER_MODEL)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_reassignments', to=settings.AUTH_USER_MODEL)),
                ('new_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_to', to='stations.guardpair')),
                ('old_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_from', to='stations.guardpair')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_reassignment_audits', to='stations.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
