# Generated by Django 5.1.15 on 2026-09-08 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_guardpair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceBookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('ROUTINE', 'Routine Check'), ('VISITOR', 'Visitor Log'), ('INCIDENT', 'Incident Report'), ('VEHICLE', 'Vehicle Entry/Exit'), ('HANDOVER', 'Shift Handover'), ('MAINTENANCE', 'Facility/Maintenance'), ('SPECIAL', 'Special Instructions')], default='ROUTINE', max_length=30)),
                ('occurrence_text', models.TextField()),
                ('check_record', models.CharField(blank=True, default='Verified & Logged', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ob_entries', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ob_entries', to='stations.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
