# Generated by Django 5.1.15 on 2026-09-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencebookentry',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
