# Generated by Django 5.1.15 on 2026-09-16 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence_book', '0002_occurrencebookentry_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OBAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Mandatory justification for amending an evidence record')),
                ('original_text_snapshot', models.TextField(help_text='Snapshot of the record text before this amendment')),
                ('amended_text', models.TextField(help_text='New text content appended as an official correction')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('amended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ob_amendments', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='occurrence_book.occurrencebookentry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
