# Generated by Django 5.1.15 on 2026-09-08 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_guardpair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRosterCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_start_date', models.DateField()),
                ('cycle_length_days', models.PositiveIntegerField(default=4)),
                ('rotation_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_cycles', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift_type', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], db_index=True, max_length=10)),
                ('is_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL)),
                ('pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='stations.guardpair')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='stations.station')),
            ],
            options={
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('clock_in_gps', models.CharField(blank=True, default='', max_length=100)),
                ('clock_out_gps', models.CharField(blank=True, default='', max_length=100)),
                ('is_late', models.BooleanField(default=False)),
                ('late_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='shifts.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_summary', models.TextField()),
                ('equipment_issued', models.TextField(blank=True, default='All inventory accounted for.')),
                ('keys_handed_over', models.TextField(blank=True, default='Master keys & padlock sets transferred.')),
                ('pending_issues', models.TextField(blank=True, default='None.')),
                ('outgoing_signed', models.BooleanField(default=True)),
                ('incoming_accepted', models.BooleanField(db_index=True, default=False)),
                ('incoming_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incoming_guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_handovers', to=settings.AUTH_USER_MODEL)),
                ('outgoing_guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_handovers', to=settings.AUTH_USER_MODEL)),
                ('outgoing_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='shifts.shift')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='stations.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['guard', 'date'], name='shifts_shif_guard_i_df30b9_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['station', 'date'], name='shifts_shif_station_35f28c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('station', 'guard', 'date', 'shift_type')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('shift', 'guard')},
        ),
    ]
