# Generated by Django 5.1.15 on 2026-09-17 00:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        ('stations', '0002_guardpair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='assignment_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Duty'), ('EXAM', 'Exam Duty'), ('ESCORT', 'Escort Duty'), ('TIME_OFF', 'Time Off'), ('RELIEF', 'Relief Duty')], db_index=True, default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='shift',
            name='duty_location',
            field=models.CharField(default='Main Campus', max_length=150),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift'), ('OFF', 'Time Off')], db_index=True, max_length=10),
        ),
        migrations.CreateModel(
            name='ExaminationPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='University Examinations', max_length=150)),
                ('venue_name', models.CharField(default='Examination Center', max_length=150)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_exam_periods', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_periods', to='stations.station')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='examination_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='shifts.examinationperiod'),
        ),
        migrations.CreateModel(
            name='TemporaryAssignmentAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_assignment', models.CharField(default='NORMAL', max_length=50)),
                ('temporary_assignment', models.CharField(default='EXAM', max_length=50)),
                ('location', models.CharField(default='Exam Venue', max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Mandatory justification / operational directive')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reassignments', to=settings.AUTH_USER_MODEL)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_reassignments', to=settings.AUTH_USER_MODEL)),
                ('original_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_reassignments', to='stations.guardpair')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
