# Generated by Django 5.1.15 on 2026-09-17 22:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shift_assignment_type_shift_duty_location_and_more'),
        ('stations', '0002_guardpair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_duty_rosters', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_rosters', to='stations.station')),
            ],
            options={
                'ordering': ['-start_date', 'station'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='shifts.dutyroster'),
        ),
        migrations.AddIndex(
            model_name='dutyroster',
            index=models.Index(fields=['station', 'start_date'], name='shifts_duty_station_4ed22a_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyroster',
            index=models.Index(fields=['station', 'end_date'], name='shifts_duty_station_00f7df_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyroster',
            index=models.Index(fields=['status'], name='shifts_duty_status_0c23f5_idx'),
        ),
    ]
