# Generated by Django 5.1.15 on 2026-09-18 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_dutyroster_shift_roster_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(db_index=True)),
                ('country_code', models.CharField(db_index=True, default='ZW', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'country_code')},
            },
        ),
        migrations.CreateModel(
            name='PublicHolidayDutyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compensated_days', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_holiday_compensations', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_duty_records', to='shifts.attendance')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_duty_records', to=settings.AUTH_USER_MODEL)),
                ('public_holiday', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_records', to='shifts.publicholiday')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_duty_record', to='shifts.shift')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guard', 'status'], name='shifts_publ_guard_i_df74a3_idx'), models.Index(fields=['public_holiday', 'guard'], name='shifts_publ_public__24bc0d_idx')],
            },
        ),
    ]
