# Generated by Django 5.1.15 on 2026-09-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_publicholiday_publicholidaydutyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='escalation_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_serious_late',
            field=models.BooleanField(default=False),
        ),
    ]
