# Generated by Django 5.1.15 on 2026-10-06 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_leavebalance_opening_balance_date_and_more'),
        ('shifts', '0005_attendance_escalation_notified_and_more'),
        ('stations', '0003_guardpairreassignmentaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('override_type', models.CharField(choices=[('LEAVE_INTERRUPTION', 'Leave Interruption for Duty'), ('OFF_DAY_CALL_IN', 'Scheduled Off-Day Call-In'), ('EMERGENCY_REINFORCEMENT', 'Emergency Station Reinforcement')], db_index=True, default='LEAVE_INTERRUPTION', max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('shift_type', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift'), ('OFF', 'Time Off')], default='DAY', max_length=10)),
                ('reason', models.TextField(help_text='Mandatory operational justification for duty override / interruption')),
                ('days_interrupted', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('compensation_days_owed', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('compensation_settled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_duty_overrides', to=settings.AUTH_USER_MODEL)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_overrides', to=settings.AUTH_USER_MODEL)),
                ('original_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_overrides', to='leave.leaveapplication')),
                ('original_off_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='off_day_overrides', to='shifts.shift')),
                ('shift_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_duty_override', to='shifts.shift')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_overrides', to='stations.station')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['guard', 'date'], name='shifts_duty_guard_i_defb7b_idx'), models.Index(fields=['station', 'date'], name='shifts_duty_station_e92751_idx'), models.Index(fields=['status'], name='shifts_duty_status_42878f_idx')],
            },
        ),
    ]
