# Generated by Django 5.1.15 on 2026-09-16 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='escalated_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
