# Generated by Django 5.1.15 on 2026-09-16 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidentreport_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Mandatory justification for amending an incident record')),
                ('original_description_snapshot', models.TextField(help_text='Snapshot of the description before this amendment')),
                ('amended_description', models.TextField(help_text='New description content appended as an official correction')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('amended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_amendments', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='incidents.incidentreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
