# Generated by Django 5.1.15 on 2026-09-16 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILURE', 'Login Failure'), ('PASSWORD_RESET_REQUEST', 'Password Reset Request'), ('PASSWORD_RESET_SUCCESS', 'Password Reset Success'), ('PASSWORD_RESET_FAILED', 'Password Reset Failed'), ('RECORD_AMENDMENT', 'Record Amendment'), ('OVERRIDE', 'Supervisor Override'), ('UNAUTHORIZED_ACCESS_ATTEMPT', 'Unauthorized Access Attempt')], db_index=True, max_length=64)),
                ('actor_username', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('target_model', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
