# Generated by Django 5.1.15 on 2026-10-06 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recordadjustmentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('LEAVE', 'Leave Management Policy'), ('ROSTER', 'Roster & Shift Rotation Policy'), ('DUTY', 'Operational Duty & Relief Policy'), ('PATROL', 'Patrol & Geofence Verification Policy'), ('ATTENDANCE', 'Attendance & Clock-In Policy'), ('COMPENSATION', 'Public Holiday & Duty Compensation Policy'), ('GEOFENCE', 'Station Perimeter & Geofence Policy'), ('GENERAL', 'General Security Operations Policy')], db_index=True, max_length=64)),
                ('title', models.CharField(max_length=150)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
