# Generated by Django 5.1.15 on 2026-10-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizationpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpolicy',
            name='policy_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='organizationpolicy',
            name='setting_value',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='organizationpolicy',
            name='category',
            field=models.CharField(choices=[('LEAVE', 'Leave Management Policy'), ('ROSTER', 'Roster & Shift Rotation Policy'), ('DUTY', 'Operational Duty & Relief Policy'), ('PATROL', 'Patrol & Geofence Verification Policy'), ('ATTENDANCE', 'Attendance & Clock-In Policy'), ('COMPENSATION', 'Public Holiday & Duty Compensation Policy'), ('GEOFENCE', 'Station Perimeter & Geofence Policy'), ('SECURITY', 'Access Control & Information Security Policy'), ('GENERAL', 'General Security Operations Policy')], db_index=True, max_length=64),
        ),
    ]
