# Generated by Django 5.1.15 on 2026-09-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginattempt_passwordresetotp_userdeactivationaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='max_attempts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='otp_code_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
