# Generated by Django 5.1.15 on 2026-09-08 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDuty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=200)),
                ('exam_title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(default='ASSIGNED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]
